name: casino_test
description: Casino test application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.2.0
  fpdart: ^0.6.0
  get_it: ^7.2.0
  http: ^0.13.4
  json_annotation: ^4.8.1
  stream_transform: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.2
  build_runner: ^2.0.0
  flutter_lints: ^2.0.1
  freezed: ^2.3.4
  json_serializable: ^6.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
